title: Fire and Lion email signatures
email: team@fireandlion.com
description: > # this means to ignore newlines until "baseurl:"
  Email signatures for Fire and Lion team members.
baseurl: "/signatures" # the subpath of your site, e.g. /blog
url: "fireandlion.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: fireandlion
github_username:  fireandlion

# Exclude from processing.
# The following items will not be processed, by default.
exclude:
  - Gemfile
  - Gemfile.lock
  - README*

# We want file names as-is
permalink: none

# Set defaults
defaults: 
  -
    scope: # Sets default page frontmatter for all files in this series (an empty string "" for path means all files).
      path: ""
    values:
      layout: "default"
